SOULBOUND_URIS = {
    "soulbound_donate_1": "ipfs://bafybeifizmsqkbb3jt6llqlrd3owjeqxzbn5kkhbyeicy46m2gfdrdtfay/TheGiftofGifting.json",
    "soulbound_donate_2": "ipfs://bafybeifizmsqkbb3jt6llqlrd3owjeqxzbn5kkhbyeicy46m2gfdrdtfay/ThePatron.json",
    "soulbound_donate_3": "ipfs://bafybeifizmsqkbb3jt6llqlrd3owjeqxzbn5kkhbyeicy46m2gfdrdtfay/Philanthropist.json",
    "soulbound_people_1": "ipfs://bafybeifizmsqkbb3jt6llqlrd3owjeqxzbn5kkhbyeicy46m2gfdrdtfay/DoubleTrouble.json",
    "soulbound_people_2": "ipfs://bafybeifizmsqkbb3jt6llqlrd3owjeqxzbn5kkhbyeicy46m2gfdrdtfay/FiveofaKind.json",
    "soulbound_people_3": "ipfs://bafybeifizmsqkbb3jt6llqlrd3owjeqxzbn5kkhbyeicy46m2gfdrdtfay/TheDecadeofGiving.json",
    "soulbound_fan_1": "ipfs://bafybeifizmsqkbb3jt6llqlrd3owjeqxzbn5kkhbyeicy46m2gfdrdtfay/Fan.json",
    "soulbound_fan_2": "ipfs://bafybeifizmsqkbb3jt6llqlrd3owjeqxzbn5kkhbyeicy46m2gfdrdtfay/TheLoyalSupporter.json",
    "soulbound_fan_3": "ipfs://bafybeifizmsqkbb3jt6llqlrd3owjeqxzbn5kkhbyeicy46m2gfdrdtfay/TheDecadeofDevotion.json",
    "soulbound_fan_1": "ipfs://bafybeifizmsqkbb3jt6llqlrd3owjeqxzbn5kkhbyeicy46m2gfdrdtfay/TheSpendingSpree.json",
    "soulbound_eth_2": "ipfs://bafybeifizmsqkbb3jt6llqlrd3owjeqxzbn5kkhbyeicy46m2gfdrdtfay/TheFinancialOdyssey.json",
    "soulbound_eth_3": "ipfs://bafybeifizmsqkbb3jt6llqlrd3owjeqxzbn5kkhbyeicy46m2gfdrdtfay/TheGrandioseWealthVenture.json",
    "soulbound_all_nfts": "ipfs://bafybeifizmsqkbb3jt6llqlrd3owjeqxzbn5kkhbyeicy46m2gfdrdtfay/TheCollector%27sTriumph%EF%80%BAMasterofAllTreasures.json",
}
