SOULBOUND_URIS = {
    "soulbound_donate_1": "https://ipfs.io/ipfs/bafybeicxnf7sgyjxeky52vbxh3csltzfhat2bczli37v4qczi24i6xvkiq/TheGiftofGifting.json",
    "soulbound_donate_2": "https://ipfs.io/ipfs/bafybeicxnf7sgyjxeky52vbxh3csltzfhat2bczli37v4qczi24i6xvkiq/ThePatron.json",
    "soulbound_donate_3": "https://ipfs.io/ipfs/bafybeicxnf7sgyjxeky52vbxh3csltzfhat2bczli37v4qczi24i6xvkiq/Philanthropist.json",
    "soulbound_people_1": "https://ipfs.io/ipfs/bafybeicxnf7sgyjxeky52vbxh3csltzfhat2bczli37v4qczi24i6xvkiq/DoubleTrouble.json",
    "soulbound_people_2": "https://ipfs.io/ipfs/bafybeicxnf7sgyjxeky52vbxh3csltzfhat2bczli37v4qczi24i6xvkiq/FiveofaKind.json",
    "soulbound_people_3": "https://ipfs.io/ipfs/bafybeicxnf7sgyjxeky52vbxh3csltzfhat2bczli37v4qczi24i6xvkiq/TheDecadeofGiving.json",
    "soulbound_fan_1": "https://ipfs.io/ipfs/bafybeicxnf7sgyjxeky52vbxh3csltzfhat2bczli37v4qczi24i6xvkiq/Fan.json",
    "soulbound_fan_2": "https://ipfs.io/ipfs/bafybeicxnf7sgyjxeky52vbxh3csltzfhat2bczli37v4qczi24i6xvkiq/TheLoyalSupporter.json",
    "soulbound_fan_3": "https://ipfs.io/ipfs/bafybeicxnf7sgyjxeky52vbxh3csltzfhat2bczli37v4qczi24i6xvkiq/TheDecadeofDevotion.json",
    "soulbound_fan_1": "https://ipfs.io/ipfs/bafybeicxnf7sgyjxeky52vbxh3csltzfhat2bczli37v4qczi24i6xvkiq/TheSpendingSpree.json",
    "soulbound_eth_2": "https://ipfs.io/ipfs/bafybeicxnf7sgyjxeky52vbxh3csltzfhat2bczli37v4qczi24i6xvkiq/TheFinancialOdyssey.json",
    "soulbound_eth_3": "https://ipfs.io/ipfs/bafybeicxnf7sgyjxeky52vbxh3csltzfhat2bczli37v4qczi24i6xvkiq/TheGrandioseWealthVenture.json",
    "soulbound_all_nfts": "https://ipfs.io/ipfs/bafybeibcqxyc4ufkmexrhi6wu2s7qc3thizng3zcjqgtgyqct6x4i4debu",
}
