dependencies:
  - OpenZeppelin/openzeppelin-contracts@5.0.0
compiler:
  solc:
    version: 0.8.21
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@5.0.0"
dotenv: .env
wallets:
  from_key_1: ${PRIVATE_KEY_1}
  from_key_2: ${PRIVATE_KEY_2}
  from_key_3: ${PRIVATE_KEY_3}
rpcs:
  infura_mainnet: ${WEB3_INFURA_PROJECT_ID}
networks:
  development:
    verify: False
  arbitrum-main-fork:
    verify: False
    users_address: "0x4D76E5Cc49091563BB3203657E11c485daAB4681"
    nft_gifts_address: "0xCF85C0DB8b670c3AADa28B47b735B085BFCF2c9d"
    soulbound_address: "0x8b0242F40b0428715475254d37853Ea13b83b610"
    deposit_asset: "0x82af49447d8a07e3bd95bd0d56f35241523fbab1" # WETH
    community_vault_address: "0x48f27B0094d907417F781294bCd9fc48C4F556fB"
  arbitrum-main:
    host: "wss://arb-mainnet.g.alchemy.com/v2/4xtrY8Y7E-DEeAFPwluzeq2HHw7Zdazm"
    verify: True
    users_address: "0x87603f7440D67a9874CE4DAAfa0C9aDF6870DFe9"
    nft_gifts_address: "0x694B9D3917D19713F795150C72EB8E1E6EAeBb13"
    soulbound_address: "0x79B83a12599BEE5192015e0480dF62b622cc36bc"
    deposit_asset: "0x82af49447d8a07e3bd95bd0d56f35241523fbab1" # WETH
    community_vault_address: "0xA62A970999cd1Ae8071F3BEC6841BA1fe7413cab"
