dependencies:
  - OpenZeppelin/openzeppelin-contracts@5.0.0
compiler:
  solc:
    version: 0.8.21
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@5.0.0"
dotenv: .env
wallets:
  from_key_1: ${PRIVATE_KEY_1}
  from_key_2: ${PRIVATE_KEY_2}
  from_key_3: ${PRIVATE_KEY_3}
  # from_key: ${PRIVATE_KEY}
rpcs:
  infura_mainnet: ${WEB3_INFURA_PROJECT_ID}
networks:
  development:
    verify: False
  arbitrum-main-fork:
    verify: False
  arbitrum-main:
    verify: True
